---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse
  - src: https://github.com/igromchenko/vector-role.git
    scm: git
    version: "1.0.0"
    name: vector-role
  - src: https://github.com/igromchenko/lighthouse-role.git
    scm: git
    version: "1.0.0"
    name: lighthouse-role